
from dataclasses import dataclass
from typing import Any, Dict, List, Optional, Tuple, Union

from transformers.trainer_utils import EvaluationStrategy
from src.models.controllers.controller_types import ControllerInputType

from src.models.adalas_opt.config_adalas_opt import AdalasOPTConfig, StaticSkipPropagationConfig, \
    StochasticDropoutPropagationConfig, PropagationConfig, PropagationMode, DynamicPropagationConfig, \
    StaticEEPropagationConfig


class DictOverwritable(object):
    '''allows to overwrite some attributes of a class with a dict'''
    def update_fields(self, dict_for_update):
        for key, value in dict_for_update.items():
            if hasattr(self, key):
                setattr(self, key, value)

@dataclass
class TrainingArgs(DictOverwritable):
    seed: int = 42
    learning_rate: float = 5e-5
    tokenized_dataset_path: str = None
    load_dataset_from_disk: bool = False #deprecated for tokenized_dataset_path
    load_model_from_disk: bool = False
    dataset: str = 'databricks/databricks-dolly-15k'
    model: str = 'facebook/opt-125M'
    prop_config: PropagationConfig = PropagationConfig()
    batch_size: int = 10
    gradient_accumulation_steps: int = 1
    gradient_checkpointing: bool = True
    train_epochs: int = 3
    max_seq_length: int = 768
    logging_steps:int = 20
    eval_strategy: str = "steps"
    eval_steps:int = 100
    save_steps:int=100
    save_strategy: str = "no"
    prompt_seq_length: float = 0.7
    from_checkpoint: bool = False
    load_best_model_at_end: bool = False,
    save_total_limit: int = 3,
    multiprocess: bool = True
    instruction_template: str = "### User:"
    response_template: str = "\n### Assistant:"
    ddp: bool = True
    skip_prompt: bool = False
    max_new_tokens: int = 200
    generate_do_sample: bool = False
    generate_temperature: float = 1.0
    fp16: bool = True
    with_cost_aware_loss: bool = False
    alpha: float = 0.0,
    save_dataset_dir: Optional[str] = None
    save_model_pretrain_dir: Optional[str] = None
    deepspeed: Optional[str] = None
    with_lora: bool = True,
    lora_rank: Optional[int] = 8
    lora_alpha: Optional[int] = 8
    lora_dropout: Optional[float] = 0.05


    

SAVED_ARGS = {
    "ee_test": TrainingArgs(
        prop_config=StaticEEPropagationConfig(early_exit_layer=9),
        batch_size=4,
        model='logs/opt-125m/databricks-dolly-15k_23-07_14-13-33/checkpoint-8000',
        train_epochs=3,
        eval_steps = 2000,
        save_dataset_dir="dolly_opt125",
        save_strategy = EvaluationStrategy.NO,
        ddp=False,
        fp16=False,
        load_model_from_disk=True,
        deepspeed='ds_config.json',
        alpha = 10,
        with_cost_aware_loss=False,
        max_seq_length=256,
        tokenized_dataset_path='dolly_opt125',
        gradient_checkpointing=False,
        with_lora=False
    ),
    "warmup_probabilistic": TrainingArgs(
        prop_config=StochasticDropoutPropagationConfig(skip_probs=[0] + [0.5] * 10 + [0]),
        batch_size=4,
        model='logs/opt-125m/databricks-dolly-15k_23-07_14-13-33/checkpoint-8000',
        train_epochs=3,
        eval_steps = 2000,
        save_strategy = EvaluationStrategy.NO,
        ddp=False,
        fp16=False,
        load_model_from_disk=True,
        deepspeed='ds_config.json',
        alpha = 10,
        with_cost_aware_loss=False,
        max_seq_length=256,
        gradient_checkpointing=True
    ),
    "controller_warmup": TrainingArgs(
        prop_config=DynamicPropagationConfig(controller_layers=[1,2,3,4,5,6,7,8,9,10]),
        batch_size=4,
        model='logs/opt-125m/databricks-dolly-15k_23-07_14-13-33/checkpoint-8000',
        train_epochs=3,
        eval_steps = 2000,
        save_strategy = EvaluationStrategy.NO,
        ddp=False,
        fp16=False,
        load_model_from_disk=True,
        deepspeed='ds_config.json',
        alpha = 3,
        with_cost_aware_loss=True,
        max_seq_length=256,
        gradient_checkpointing=True
    ),
    "full_prop_opt125_args": TrainingArgs(
        prop_config=PropagationConfig(),
        batch_size=4,
        model='facebook/opt-125m',
        train_epochs=3,
        eval_steps = 1000,
        save_strategy = "steps",
        save_steps = 1000,
        fp16=False,
        gradient_checkpointing=False,
        ddp=False,
        max_seq_length=256,
        deepspeed='ds_config.json',
        gradient_accumulation_steps=1,
    ),
    "full_prop_args": TrainingArgs(
        prop_config=PropagationConfig(),
        batch_size=4,
        model='facebook/opt-350m',
        train_epochs=3,
        eval_steps = 200,
        save_strategy = "epoch",
        ddp=True,
        deepspeed='ds_config.json',
        gradient_accumulation_steps=2,
        max_new_tokens=10,
        fp16 = False
    ),
    "warmup_gumbel_350_args": TrainingArgs(
        learning_rate=5e-5,
        prop_config=DynamicPropagationConfig(controller_layers=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22]),
        batch_size=4,
        load_model_from_disk=True,
        model='results/opt-350m/databricks-dolly-15k_25-07_20-17-48/checkpoint-564',
        train_epochs=3,
        max_seq_length=768,
        eval_strategy = "epoch",
        save_strategy = "epoch",
        ddp=True,
        deepspeed='ds_config.json',
        gradient_accumulation_steps=2,
        fp16 = False
    ),
    "warmup_gumbel_1.3_args": TrainingArgs(
        prop_config=DynamicPropagationConfig(controller_layers=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22]),
        batch_size=2,
        load_model_from_disk=True,
        model='results/opt-1.3b/full_prop_25-07_23-13-54/checkpoint-561',
        train_epochs=3,
        max_seq_length=768,
        eval_strategy = "epoch",
        save_strategy = "epoch",
        ddp=True,
        deepspeed='ds_config.json',
        gradient_accumulation_steps=4,
        fp16 = False
    ),
    "warmup_gumbel_fixed_input_1.3_args": TrainingArgs(
        prop_config=DynamicPropagationConfig(controller_layers=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22],with_fixed_input = True),
        batch_size=3,
        load_model_from_disk=True,
        model='results/opt-1.3b/full_prop_25-07_23-13-54/checkpoint-561',
        train_epochs=3,
        max_seq_length=768,
        eval_strategy = "epoch",
        save_strategy = "epoch",
        alpha = 0,
        with_cost_aware_loss=True,
        ddp=True,
        deepspeed='ds_config.json',
        gradient_accumulation_steps=4,
        fp16 = False
    ),
    "warmup_gumbel_alpha_10_1.3_args": TrainingArgs(
        prop_config=DynamicPropagationConfig(controller_layers=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22]),
        batch_size=2,
        load_model_from_disk=True,
        model='results/opt-1.3b/full_prop_25-07_23-13-54/checkpoint-561',
        train_epochs=3,
        max_seq_length=768,
        eval_strategy = "epoch",
        save_strategy = "epoch",
        alpha = 10,
        with_cost_aware_loss=True,
        ddp=True,
        deepspeed='ds_config.json',
        gradient_accumulation_steps=4,
        fp16 = False
    ),
    "eval_warmup_gumbel_1.3_args": TrainingArgs(
        prop_config=DynamicPropagationConfig(controller_layers=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22]),
        batch_size=3,
        load_model_from_disk=True,
        model='results/opt-1.3b/dynamic_alpha_0_26-07_03-03-54/checkpoint-561',
        train_epochs=3,
        max_seq_length=768,
        eval_strategy = "epoch",
        save_strategy = "epoch",
        ddp=True,
        deepspeed=None,
        gradient_accumulation_steps=4,
        fp16 = False
    ),

    "eval_probabilistic_1.3_args": TrainingArgs(
        prop_config=StochasticDropoutPropagationConfig(skip_probs=[0.0,0.1641,0.1373,0.4542,0.2786,0.3276,0.4686,0.1297,0.2844,0.1525,0.1881,0.157,0.0884,0.1019,0.0437,0.0808,0.0825,0.0242,0.0901,0.0718,0.0399,0.0171,0.0454,0.0]),
        batch_size=3,
        load_model_from_disk=True,
        model='results/opt-1.3b/dynamic_alpha_0_26-07_03-03-54/checkpoint-561',
        train_epochs=3,
        max_seq_length=768,
        eval_strategy = "epoch",
        save_strategy = "epoch",
        ddp=True,
        deepspeed=None,
        gradient_accumulation_steps=4,
        fp16 = False
    ),
    "eval_probabilistic_alpha_6_1.3_args": TrainingArgs(
        prop_config=StochasticDropoutPropagationConfig(skip_probs=[0.0,0.1749,0.153,0.4628,0.3405,0.5163,0.5705,0.2055,0.5148,0.3686,0.5262,0.4738,0.4589,0.4907,0.4039,0.3143,0.4187,0.2617,0.2966,0.2723,0.3062,0.3854,0.6808,0.0]),
        batch_size=4,
        load_model_from_disk=True,
        model='results/opt-1.3b/dynamic_alpha_6_28-07_02-14-44/checkpoint-561',
        train_epochs=3,
        max_seq_length=768,
        eval_strategy = "epoch",
        save_strategy = "epoch",
        ddp=True,
        deepspeed=None,
        gradient_accumulation_steps=4,
        fp16 = False
    ),
    "eval_ULS_1.0x_1.3_args": TrainingArgs(
        prop_config=PropagationConfig(),
        batch_size=4,
        load_model_from_disk=True,
        model='results/opt-1.3b/full_prop_25-07_23-13-54/checkpoint-561',
        train_epochs=3,
        max_seq_length=768,
        eval_strategy = "epoch",
        save_strategy = "epoch",
        ddp=True,
        deepspeed=None,
        gradient_accumulation_steps=4,
        fp16 = False
    ),
    "eval_ULS_1.5x_1.3_args": TrainingArgs(
        prop_config=StaticSkipPropagationConfig(skip_layers=[1,4,7,10,13,16,19,22]),
        batch_size=4,
        load_model_from_disk=True,
        model='results/opt-1.3b/full_prop_25-07_23-13-54/checkpoint-561',
        train_epochs=3,
        max_seq_length=768,
        eval_strategy = "epoch",
        save_strategy = "epoch",
        ddp=True,
        deepspeed=None,
        gradient_accumulation_steps=4,
        fp16 = False
    ),
    "eval_ULS_1.85x_1.3_args": TrainingArgs(
        prop_config=StaticSkipPropagationConfig(skip_layers=[1,3,5,7,9,11,13,15,17,19,21]),
        batch_size=4,
        load_model_from_disk=True,
        model='results/opt-1.3b/full_prop_25-07_23-13-54/checkpoint-561',
        train_epochs=3,
        max_seq_length=768,
        eval_strategy = "epoch",
        save_strategy = "epoch",
        ddp=True,
        deepspeed=None,
        gradient_accumulation_steps=4,
        fp16 = False
    ),
    "eval_ULS_3.0x_1.3_args": TrainingArgs(
        prop_config=StaticSkipPropagationConfig(skip_layers=[1,2,4,5,7,8,10,11,13,14,16,17,18,20,21,22]),
        batch_size=4,
        load_model_from_disk=True,
        model='results/opt-1.3b/full_prop_25-07_23-13-54/checkpoint-561',
        train_epochs=3,
        max_seq_length=768,
        eval_strategy = "epoch",
        save_strategy = "epoch",
        ddp=True,
        deepspeed=None,
        gradient_accumulation_steps=4,
        fp16 = False
    ),
    "full_prop_125_args": TrainingArgs(
        prop_config=PropagationConfig(),
        batch_size=4,
        model='facebook/opt-125m',
        train_epochs=3,
        max_seq_length=256,
        eval_strategy = "epoch",
        save_strategy = "epoch",
        ddp=True,
        deepspeed='ds_config.json',
        gradient_accumulation_steps=2,
        max_new_tokens=100,
        fp16 = False
    ),
    "full_prop_350_args": TrainingArgs(
        prop_config=PropagationConfig(),
        batch_size=4,
        model='facebook/opt-350m',
        train_epochs=3,
        max_seq_length=768,
        eval_strategy = "epoch",
        save_strategy = "epoch",
        ddp=True,
        deepspeed='ds_config.json',
        gradient_accumulation_steps=2,
        fp16 = False
    ),
    "full_prop_1.3_args": TrainingArgs(
        prop_config=PropagationConfig(),
        batch_size=2,
        model='facebook/opt-1.3b',
        train_epochs=3,
        max_seq_length=768,
        eval_strategy = "epoch",
        save_strategy = "epoch",
        ddp=True,
        deepspeed='ds_config.json',
        gradient_accumulation_steps=3,
        fp16 = False
    ),
    "SM_full_prop_1.3_args": TrainingArgs(
        dataset='Samsung/samsum',
        prop_config=PropagationConfig(),
        batch_size=3,
        model='facebook/opt-1.3b',
        train_epochs=3,
        max_seq_length=768,
        instruction_template = "### Dialogue:",
        response_template= "\n### Summary:",
        eval_strategy = "epoch",
        save_strategy = "epoch",
        ddp=True,
        deepspeed='ds_config.json',
        gradient_accumulation_steps=4,
        fp16 = False
    ),
    "SM_warmup_gumbel_alpha_0_1.3_args": TrainingArgs(
        dataset='Samsung/samsum',
        prop_config=DynamicPropagationConfig(controller_layers=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22]),
        batch_size=3,
        load_model_from_disk=True,
        model='results/opt-1.3b/SAMSUM/full_prop_30-07_23-59-18/checkpoint-459',
        train_epochs=2,
        max_seq_length=768,
        instruction_template = "### Dialogue:",
        response_template= "\n### Summary:",
        eval_strategy = "epoch",
        save_strategy = "epoch",
        alpha = 0,
        with_cost_aware_loss=True,
        ddp=True,
        deepspeed='ds_config.json',
        gradient_accumulation_steps=3,
        fp16 = False
    ),
    "SM_warmup_gumbel_3L_alpha_0_1.3_args": TrainingArgs(
        dataset='Samsung/samsum',
        prop_config=DynamicPropagationConfig(controller_layers=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22],layers=3,divisor=8),
        batch_size=3,
        load_model_from_disk=True,
        model='results/opt-1.3b/SAMSUM/full_prop_30-07_23-59-18/checkpoint-459',
        train_epochs=3,
        max_seq_length=768,
        instruction_template = "### Dialogue:",
        response_template= "\n### Summary:",
        eval_strategy = "epoch",
        save_strategy = "epoch",
        alpha = 0,
        with_cost_aware_loss=True,
        ddp=True,
        deepspeed='ds_config.json',
        gradient_accumulation_steps=3,
        fp16 = False
    ),
    "SM_warmup_gumbel_pos_alpha_0_1.3_args": TrainingArgs(
        dataset='Samsung/samsum',
        prop_config=DynamicPropagationConfig(controller_layers=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22], controller_input_type=ControllerInputType.POS_EMBEDS),
        batch_size=3,
        load_model_from_disk=True,
        model='results/opt-1.3b/SAMSUM/full_prop_30-07_23-59-18/checkpoint-459',
        train_epochs=2,
        max_seq_length=768,
        instruction_template = "### Dialogue:",
        response_template= "\n### Summary:",
        eval_strategy = "epoch",
        save_strategy = "epoch",
        alpha = 0,
        with_cost_aware_loss=True,
        ddp=True,
        deepspeed='ds_config.json',
        gradient_accumulation_steps=3,
        fp16 = False
    ),
    "SM_warmup_gumbel_inpEmb_alpha_0_1.3_args": TrainingArgs(
        dataset='Samsung/samsum',
        prop_config=DynamicPropagationConfig(controller_layers=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22], controller_input_type=ControllerInputType.INPUTS_EMBEDS),
        batch_size=3,
        load_model_from_disk=True,
        model='results/opt-1.3b/SAMSUM/full_prop_30-07_23-59-18/checkpoint-459',
        train_epochs=2,
        max_seq_length=768,
        instruction_template = "### Dialogue:",
        response_template= "\n### Summary:",
        eval_strategy = "epoch",
        save_strategy = "epoch",
        alpha = 0,
        with_cost_aware_loss=True,
        ddp=True,
        deepspeed='ds_config.json',
        gradient_accumulation_steps=3,
        fp16 = False
    ),
    "SM_warmup_gumbel_initial_alpha_0_1.3_args": TrainingArgs(
        dataset='Samsung/samsum',
        prop_config=DynamicPropagationConfig(controller_layers=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22], controller_input_type=ControllerInputType.INITIAL_STATE),
        batch_size=3,
        load_model_from_disk=True,
        model='results/opt-1.3b/SAMSUM/full_prop_30-07_23-59-18/checkpoint-459',
        train_epochs=2,
        max_seq_length=768,
        instruction_template = "### Dialogue:",
        response_template= "\n### Summary:",
        eval_strategy = "epoch",
        save_strategy = "epoch",
        alpha = 0,
        with_cost_aware_loss=True,
        ddp=True,
        deepspeed='ds_config.json',
        gradient_accumulation_steps=3,
        fp16 = False
    ),
    "SM_warmup_fixed_gumbel_alpha_0_1.3_args": TrainingArgs(
        dataset='Samsung/samsum',
        prop_config=DynamicPropagationConfig(controller_layers=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22],with_fixed_input = True),
        batch_size=3,
        load_model_from_disk=True,
        model='results/opt-1.3b/SAMSUM/full_prop_30-07_23-59-18/checkpoint-459',
        train_epochs=2,
        max_seq_length=768,
        instruction_template = "### Dialogue:",
        response_template= "\n### Summary:",
        eval_strategy = "epoch",
        save_strategy = "epoch",
        alpha = 0,
        with_cost_aware_loss=True,
        ddp=True,
        deepspeed='ds_config.json',
        gradient_accumulation_steps=3,
        fp16 = False
    ),
    "SM_eval_gumbel_alpha_0.5_1.3_args": TrainingArgs(
        dataset='Samsung/samsum',
        prop_config=DynamicPropagationConfig(controller_layers=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22]),
        batch_size=3,
        load_model_from_disk=True,
        model='results/opt-1.3b/SAMSUM/dynamic_alpha_0.5_06-08_16-28-53/checkpoint-408',
        train_epochs=2,
        max_seq_length=768,
        instruction_template = "### Dialogue:",
        response_template= "\n### Summary:",
        eval_strategy = "epoch",
        save_strategy = "epoch",
        ddp=True,
        deepspeed=None,
        gradient_accumulation_steps=3,
        fp16 = False
    ),
    "SM_eval_gumbel_3L_alpha_2_1.3_args": TrainingArgs(
        dataset='Samsung/samsum',
        prop_config=DynamicPropagationConfig(controller_layers=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22],layers=3,divisor=8),
        batch_size=3,
        load_model_from_disk=True,
        model='results/opt-1.3b/SAMSUM/3L_dynamic_alpha_2_06-08_22-51-21/checkpoint-612',
        train_epochs=2,
        max_seq_length=768,
        instruction_template = "### Dialogue:",
        response_template= "\n### Summary:",
        eval_strategy = "epoch",
        save_strategy = "epoch",
        ddp=True,
        deepspeed=None,
        gradient_accumulation_steps=3,
        fp16 = False
    ),
    "SM_eval_fixed_gumbel_alpha_0.5_1.3_args": TrainingArgs(
        dataset='Samsung/samsum',
        prop_config=DynamicPropagationConfig(controller_layers=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22],with_fixed_input = True),
        batch_size=3,
        load_model_from_disk=True,
        model='results/opt-1.3b/SAMSUM/fixed_input_alpha_0.5_06-08_19-30-28/checkpoint-408',
        train_epochs=2,
        max_seq_length=768,
        instruction_template = "### Dialogue:",
        response_template= "\n### Summary:",
        eval_strategy = "epoch",
        save_strategy = "epoch",
        ddp=True,
        deepspeed=None,
        gradient_accumulation_steps=3,
        fp16 = False
    ),
    "SM_eval_fixed_gumbel_alpha_2_1.3_args": TrainingArgs(
        dataset='Samsung/samsum',
        prop_config=DynamicPropagationConfig(controller_layers=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22],with_fixed_input = True),
        batch_size=3,
        load_model_from_disk=True,
        model='results/opt-1.3b/SAMSUM/fixed_input_alpha_2_07-08_16-04-21/checkpoint-408',
        train_epochs=2,
        max_seq_length=768,
        instruction_template = "### Dialogue:",
        response_template= "\n### Summary:",
        eval_strategy = "epoch",
        save_strategy = "epoch",
        ddp=True,
        deepspeed=None,
        gradient_accumulation_steps=3,
        fp16 = False
    ),
    "SM_eval_fixed_gumbel_alpha_6_1.3_args": TrainingArgs(
        dataset='Samsung/samsum',
        prop_config=DynamicPropagationConfig(controller_layers=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22],with_fixed_input = True),
        batch_size=3,
        load_model_from_disk=True,
        model='results/opt-1.3b/SAMSUM/fixed_input_alpha_6_07-08_17-59-01/checkpoint-408',
        train_epochs=2,
        max_seq_length=768,
        instruction_template = "### Dialogue:",
        response_template= "\n### Summary:",
        eval_strategy = "epoch",
        save_strategy = "epoch",
        ddp=True,
        deepspeed=None,
        gradient_accumulation_steps=3,
        fp16 = False
    ),
    "SM_eval_gumbel_alpha_2_1.3_args": TrainingArgs(
        dataset='Samsung/samsum',
        prop_config=DynamicPropagationConfig(controller_layers=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22]),
        batch_size=3,
        load_model_from_disk=True,
        model='results/opt-1.3b/SAMSUM/dynamic_alpha_2_05-08_16-14-46/checkpoint-408',
        train_epochs=2,
        max_seq_length=768,
        instruction_template = "### Dialogue:",
        response_template= "\n### Summary:",
        eval_strategy = "epoch",
        save_strategy = "epoch",
        ddp=True,
        deepspeed=None,
        gradient_accumulation_steps=3,
        fp16 = False
    ),
    "SM_eval_gumbel_alpha_6_1.3_args": TrainingArgs(
        dataset='Samsung/samsum',
        prop_config=DynamicPropagationConfig(controller_layers=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22]),
        batch_size=3,
        load_model_from_disk=True,
        model='results/opt-1.3b/SAMSUM/dynamic_alpha_6_05-08_17-47-23/checkpoint-408',
        train_epochs=2,
        max_seq_length=768,
        instruction_template = "### Dialogue:",
        response_template= "\n### Summary:",
        eval_strategy = "epoch",
        save_strategy = "epoch",
        ddp=True,
        deepspeed=None,
        gradient_accumulation_steps=3,
        fp16 = False
    ),
    "SM_eval_gumbel_alpha_10_1.3_args": TrainingArgs(
        dataset='Samsung/samsum',
        prop_config=DynamicPropagationConfig(controller_layers=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22]),
        batch_size=3,
        load_model_from_disk=True,
        model='results/opt-1.3b/SAMSUM/dynamic_alpha_10_05-08_19-20-25/checkpoint-408',
        train_epochs=2,
        max_seq_length=768,
        instruction_template = "### Dialogue:",
        response_template= "\n### Summary:",
        eval_strategy = "epoch",
        save_strategy = "epoch",
        ddp=True,
        deepspeed=None,
        gradient_accumulation_steps=3,
        fp16 = False
    ),
    "SM_eval_inpEmb_gumbel_alpha_2_1.3_args": TrainingArgs(
        dataset='Samsung/samsum',
        prop_config=DynamicPropagationConfig(controller_layers=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22], controller_input_type=ControllerInputType.INPUTS_EMBEDS),
        batch_size=3,
        load_model_from_disk=True,
        model='results/opt-1.3b/SAMSUM/inpEmb_dynamic_alpha_2_10std_08-08_00-01-31/checkpoint-408',
        train_epochs=2,
        max_seq_length=768,
        instruction_template = "### Dialogue:",
        response_template= "\n### Summary:",
        eval_strategy = "epoch",
        save_strategy = "epoch",
        ddp=True,
        deepspeed=None,
        gradient_accumulation_steps=3,
        fp16 = False
    ),
    "SM_eval_inpEmb_gumbel_alpha_6_1.3_args": TrainingArgs(
        dataset='Samsung/samsum',
        prop_config=DynamicPropagationConfig(controller_layers=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22], controller_input_type=ControllerInputType.INPUTS_EMBEDS),
        batch_size=3,
        load_model_from_disk=True,
        model='results/opt-1.3b/SAMSUM/inpEmb_dynamic_alpha_6_10std_08-08_03-05-54/checkpoint-408',
        train_epochs=2,
        max_seq_length=768,
        instruction_template = "### Dialogue:",
        response_template= "\n### Summary:",
        eval_strategy = "epoch",
        save_strategy = "epoch",
        ddp=True,
        deepspeed=None,
        gradient_accumulation_steps=3,
        fp16 = False
    ),
    "SM_eval_pos_gumbel_alpha_2_1.3_args": TrainingArgs(
        dataset='Samsung/samsum',
        prop_config=DynamicPropagationConfig(controller_layers=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22], controller_input_type=ControllerInputType.POS_EMBEDS),
        batch_size=3,
        load_model_from_disk=True,
        model='results/opt-1.3b/SAMSUM/pos_dynamic_alpha_2_10std_08-08_04-41-29/checkpoint-408',
        train_epochs=2,
        max_seq_length=768,
        instruction_template = "### Dialogue:",
        response_template= "\n### Summary:",
        eval_strategy = "epoch",
        save_strategy = "epoch",
        ddp=True,
        deepspeed=None,
        gradient_accumulation_steps=3,
        fp16 = False
    ),
    "SM_eval_pos_gumbel_alpha_6_1.3_args": TrainingArgs(
        dataset='Samsung/samsum',
        prop_config=DynamicPropagationConfig(controller_layers=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22], controller_input_type=ControllerInputType.POS_EMBEDS),
        batch_size=3,
        load_model_from_disk=True,
        model='results/opt-1.3b/SAMSUM/pos_dynamic_alpha_6_10std_08-08_06-18-21/checkpoint-408',
        train_epochs=2,
        max_seq_length=768,
        instruction_template = "### Dialogue:",
        response_template= "\n### Summary:",
        eval_strategy = "epoch",
        save_strategy = "epoch",
        ddp=True,
        deepspeed=None,
        gradient_accumulation_steps=3,
        fp16 = False
    ),
    "SM_eval_initial_gumbel_alpha_2_1.3_args": TrainingArgs(
        dataset='Samsung/samsum',
        prop_config=DynamicPropagationConfig(controller_layers=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22], controller_input_type=ControllerInputType.INITIAL_STATE),
        batch_size=3,
        load_model_from_disk=True,
        model='results/opt-1.3b/SAMSUM/initial_dynamic_alpha_2_10std_08-08_07-54-21/checkpoint-408',
        train_epochs=2,
        max_seq_length=768,
        instruction_template = "### Dialogue:",
        response_template= "\n### Summary:",
        eval_strategy = "epoch",
        save_strategy = "epoch",
        ddp=True,
        deepspeed=None,
        gradient_accumulation_steps=3,
        fp16 = False
    ),
    "SM_eval_initial_gumbel_alpha_6_1.3_args": TrainingArgs(
        dataset='Samsung/samsum',
        prop_config=DynamicPropagationConfig(controller_layers=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22], controller_input_type=ControllerInputType.INITIAL_STATE),
        batch_size=3,
        load_model_from_disk=True,
        model='results/opt-1.3b/SAMSUM/initial_dynamic_alpha_6_10std_08-08_09-30-17/checkpoint-408',
        train_epochs=2,
        max_seq_length=768,
        instruction_template = "### Dialogue:",
        response_template= "\n### Summary:",
        eval_strategy = "epoch",
        save_strategy = "epoch",
        ddp=True,
        deepspeed=None,
        gradient_accumulation_steps=3,
        fp16 = False
    ),
    "SM_eval_probabilistic_alpha_2_1.3_args": TrainingArgs(
        dataset='Samsung/samsum',
        prop_config=StochasticDropoutPropagationConfig(skip_probs=[0.0,0.3209,0.4434,0.7166,0.709,0.8507,0.8591,0.425,0.8083,0.67,0.658,0.5243,0.6533,0.5899,0.5706,0.3088,0.4687,0.2565,0.2915,0.2767,0.4053,0.4549,0.6448,0.0]),
        batch_size=3,
        load_model_from_disk=True,
        model='results/opt-1.3b/SAMSUM/dynamic_alpha_2_05-08_16-14-46/checkpoint-408',
        train_epochs=2,
        max_seq_length=768,
        instruction_template = "### Dialogue:",
        response_template= "\n### Summary:",
        eval_strategy = "epoch",
        save_strategy = "epoch",
        ddp=True,
        deepspeed=None,
        gradient_accumulation_steps=3,
        fp16 = False
    ),
    "SM_warmup_ULS_1.0x_1.3_args": TrainingArgs(
        dataset='Samsung/samsum',
        prop_config=PropagationConfig(),
        batch_size=3,
        load_model_from_disk=True,
        model='results/opt-1.3b/SAMSUM/full_prop_30-07_23-59-18/checkpoint-459',
        train_epochs=2,
        max_seq_length=768,
        instruction_template = "### Dialogue:",
        response_template= "\n### Summary:",
        eval_strategy = "epoch",
        save_strategy = "epoch",
        ddp=True,
        deepspeed='ds_config.json',
        gradient_accumulation_steps=3,
        fp16 = False
    ),
    "SM_warmup_ULS_1.5x_1.3_args": TrainingArgs(
        dataset='Samsung/samsum',
        prop_config=StaticSkipPropagationConfig(skip_layers=[1,4,7,10,13,16,19,22]),
        batch_size=3,
        load_model_from_disk=True,
        model='results/opt-1.3b/SAMSUM/full_prop_30-07_23-59-18/checkpoint-459',
        train_epochs=2,
        max_seq_length=768,
        instruction_template = "### Dialogue:",
        response_template= "\n### Summary:",
        eval_strategy = "epoch",
        save_strategy = "epoch",
        ddp=True,
        deepspeed='ds_config.json',
        gradient_accumulation_steps=3,
        fp16 = False
    ),
    "SM_warmup_ULS_1.85x_1.3_args": TrainingArgs(
        dataset='Samsung/samsum',
        prop_config=StaticSkipPropagationConfig(skip_layers=[1,3,5,7,9,11,13,15,17,19,21]),
        batch_size=3,
        load_model_from_disk=True,
        model='results/opt-1.3b/SAMSUM/full_prop_30-07_23-59-18/checkpoint-459',
        train_epochs=2,
        max_seq_length=768,
        instruction_template = "### Dialogue:",
        response_template= "\n### Summary:",
        eval_strategy = "epoch",
        save_strategy = "epoch",
        ddp=True,
        deepspeed='ds_config.json',
        gradient_accumulation_steps=3,
        fp16 = False
    ),
    "SM_warmup_ULS_3.0x_1.3_args": TrainingArgs(
        dataset='Samsung/samsum',
        prop_config=StaticSkipPropagationConfig(skip_layers=[1,2,4,5,7,8,10,11,13,14,16,17,18,20,21,22]),
        batch_size=3,
        load_model_from_disk=True,
        model='results/opt-1.3b/SAMSUM/full_prop_30-07_23-59-18/checkpoint-459',
        train_epochs=2,
        max_seq_length=768,
        instruction_template = "### Dialogue:",
        response_template= "\n### Summary:",
        eval_strategy = "epoch",
        save_strategy = "epoch",
        ddp=True,
        deepspeed='ds_config.json',
        gradient_accumulation_steps=3,
        fp16 = False
    ),
    "SM_eval_ULS_1.0x_1.3_args": TrainingArgs(
        dataset='Samsung/samsum',
        save_dataset_dir='samsum',
        tokenized_dataset_path='samsum',
        prop_config=PropagationConfig(),
        batch_size=4,
        load_model_from_disk=True,
        model='results/opt-1.3b/SAMSUM/full_prop_30-07_23-59-18/checkpoint-459',
        train_epochs=3,
        max_seq_length=768,
        instruction_template = "### Dialogue:",
        response_template= "\n### Summary:",
        eval_strategy = "epoch",
        save_strategy = "epoch",
        ddp=True,
        deepspeed=None,
        gradient_accumulation_steps=4,
        fp16 = False
    ),
    "SM_eval_ULS_1.5x_1.3_args": TrainingArgs(
        dataset='Samsung/samsum',
        prop_config=StaticSkipPropagationConfig(skip_layers=[1,4,7,10,13,16,19,22]),
        batch_size=4,
        load_model_from_disk=True,
        model='results/opt-1.3b/SAMSUM/ULS_1.5x_02-08_20-21-23/checkpoint-408',
        train_epochs=3,
        max_seq_length=768,
        instruction_template = "### Dialogue:",
        response_template= "\n### Summary:",
        eval_strategy = "epoch",
        save_strategy = "epoch",
        ddp=True,
        deepspeed=None,
        gradient_accumulation_steps=4,
        fp16 = False
    ),
    "SM_eval_ULS_1.85x_1.3_args": TrainingArgs(
        dataset='Samsung/samsum',
        prop_config=StaticSkipPropagationConfig(skip_layers=[1,3,5,7,9,11,13,15,17,19,21]),
        batch_size=4,
        load_model_from_disk=True,
        model='results/opt-1.3b/SAMSUM/ULS_1.85x_02-08_21-51-49/checkpoint-408',
        train_epochs=3,
        max_seq_length=768,
        instruction_template = "### Dialogue:",
        response_template= "\n### Summary:",
        eval_strategy = "epoch",
        save_strategy = "epoch",
        ddp=True,
        deepspeed=None,
        gradient_accumulation_steps=4,
        fp16 = False
    ),
    "SM_eval_ULS_3.0x_1.3_args": TrainingArgs(
        dataset='Samsung/samsum',
        prop_config=StaticSkipPropagationConfig(skip_layers=[1,2,4,5,7,8,10,11,13,14,16,17,18,20,21,22]),
        batch_size=4,
        load_model_from_disk=True,
        model='results/opt-1.3b/SAMSUM/ULS_3.0x_02-08_23-22-30/checkpoint-408',
        train_epochs=3,
        max_seq_length=768,
        instruction_template = "### Dialogue:",
        response_template= "\n### Summary:",
        eval_strategy = "epoch",
        save_strategy = "epoch",
        ddp=True,
        deepspeed=None,
        gradient_accumulation_steps=4,
        fp16 = False
    ),
    "static_skip_args_load": TrainingArgs(
        prop_config=StaticSkipPropagationConfig(skip_layers=[2, 6, 8]),
        batch_size=5,
        train_epochs=3,
        load_dataset_from_disk=True,
        load_model_from_disk=True,
        dataset='dolly-15k',
        model="results/pre_train/opt-125M-static-skip",
        deepspeed='ds_config.json'
    ),
    "static_skip_args": TrainingArgs(
        prop_config=StaticSkipPropagationConfig(skip_layers=[2, 6, 8]),
        batch_size=10,
        train_epochs=3,
        fp16=False,
        ddp=False,
    ),
    "stochastic_dropout_args": TrainingArgs(
        prop_config=StochasticDropoutPropagationConfig(skip_probs=[0.0]*4 + [0.3]*8),
        batch_size=10,
        train_epochs=3,
    ),
    "eval_full_prop_125_args": TrainingArgs(
        prop_config=PropagationConfig(),
        batch_size=4,
        model='results/opt-125m/databricks-dolly-15k_24-07_10-17-36/checkpoint-1501',
        load_model_from_disk = True,
        train_epochs=3,
        max_seq_length=256,
        eval_strategy = "epoch",
        save_strategy = "epoch",
        ddp=False,
        deepspeed='ds_config.json',
        gradient_accumulation_steps=2,
        max_new_tokens=100,
        fp16 = False
    ),
    "eval_full_prop_350_args": TrainingArgs(
        prop_config=PropagationConfig(),
        batch_size=4,
        model='results/opt-350m/databricks-dolly-15k_23-07_21-08-20/checkpoint-564',
        load_model_from_disk = True,
        train_epochs=3,
        max_seq_length=768,
        eval_strategy = "epoch",
        save_strategy = "epoch",
        ddp=False,
        deepspeed='ds_config.json',
        gradient_accumulation_steps=2,
        fp16 = False
    ),
}


